format_version: 2
pipelines:
  TestPipeline:
    group: SamplePipeline
    materials:
      backend:
        git: https://github.com/kumardevanmaha/booksapp
        branch: master
    stages:
      - Build:
          clean_workspace: true
          jobs:
            Build:
              tasks:
                - mvn compile
                - mvn package
      